import sys
import os
from pathlib import Path
import asyncio

# Add the local A2A SDK to the path
SDK_PATH = Path(__file__).parents[1] / ".a2a_source" / "src"
if str(SDK_PATH) not in sys.path:
    sys.path.insert(0, str(SDK_PATH))

# Ensure GCP configuration is present for Vertex AI
os.environ["GOOGLE_CLOUD_PROJECT"] = "mcp-playground-122025"
os.environ["GOOGLE_CLOUD_LOCATION"] = "us-central1"
os.environ["GOOGLE_GENAI_USE_VERTEXAI"] = "1"

import uvicorn
import logging

# A2A SDK Imports
from a2a.server.agent_execution.agent_executor import AgentExecutor
from a2a.server.agent_execution.context import RequestContext
from a2a.server.events.event_queue import EventQueue
from a2a.server.apps.jsonrpc.starlette_app import A2AStarletteApplication
from a2a.server.tasks.inmemory_task_store import InMemoryTaskStore
from a2a.server.request_handlers.default_request_handler import DefaultRequestHandler
from a2a.server.request_handlers.jsonrpc_handler import JSONRPCHandler
from a2a.types import AgentCard, AgentCapabilities, AgentSkill
from a2a.utils.message import new_agent_text_message

from marketing_app.agent import get_marketing_agent
from google.adk.runners import Runner
from google.adk.sessions import InMemorySessionService as ADKInMemorySessionService
from google.genai import types as genai_types
import uuid

# Configure logging
logging.basicConfig(level=logging.INFO)
logger = logging.getLogger("marketing_server")

class MarketingAgentExecutor(AgentExecutor):
    """
    Adapts the Google ADK Agent to the A2A AgentExecutor interface.
    """
    def __init__(self):
        self.agent = get_marketing_agent()
        # We can reuse the service for stateless/ephemeral sessions
        self.session_service = ADKInMemorySessionService()

    async def execute(self, context: RequestContext, event_queue: EventQueue) -> None:
        """
        Executes a task by delegating to the ADK Agent Runner.
        """
        try:
            logger.info(f"Received request: {context.message.message_id}")
            
            # Extract prompt
            if not context.message.parts:
                await event_queue.enqueue_event(new_agent_text_message("Error: No message content provided."))
                return
            
            # Extract prompt
            prompt = "Start conversation"
            if context.message.parts:
                part = context.message.parts[0]
                # Handle A2A Part object structure (RootModel or Union)
                if hasattr(part, 'root') and hasattr(part.root, 'text'):
                    prompt = part.root.text
                elif hasattr(part, 'text'):
                    prompt = part.text
                else:
                    prompt = str(part)

            # Create a unique session ID for this interaction
            session_id = f"marketing-{uuid.uuid4().hex[:8]}"
            user_id = "a2a_client"

            # Initialize ADK Runner
            runner = Runner(
                agent=self.agent,
                app_name="marketing_app",
                session_service=self.session_service
            )

            # Create ADK Session
            await self.session_service.create_session(
                app_name="marketing_app",
                user_id=user_id,
                session_id=session_id
            )

            response_found = False
            
            # Run the agent
            async for event in runner.run_async(
                user_id=user_id,
                session_id=session_id,
                new_message=genai_types.Content(role="user", parts=[genai_types.Part(text=prompt)])
            ):
                # We typically wait for the final response in a single-turn request
                if event.is_final_response() and event.content and event.content.parts:
                    response_text = event.content.parts[0].text
                    await event_queue.enqueue_event(new_agent_text_message(response_text))
                    response_found = True
                    logger.info("Response sent")
            
            if not response_found:
                 await event_queue.enqueue_event(new_agent_text_message("No response generated by agent."))

        except Exception as e:
            logger.error(f"Error executing agent: {e}", exc_info=True)
            await event_queue.enqueue_event(new_agent_text_message(f"Error executing marketing agent: {str(e)}"))

    async def cancel(self, context: RequestContext, event_queue: EventQueue) -> None:
        logger.warning("Cancel requested but not implemented.")
        pass

def create_app():
    agent_card = AgentCard(
        name="Marketing Agent",
        description="A creative marketing expert who writes social media copy.",
        url="http://localhost:8001/",
        version="1.0.0",
        default_input_modes=["text"],
        default_output_modes=["text"],
        capabilities=AgentCapabilities(streaming=False),
        skills=[
            AgentSkill(
                id="marketing_consultation",
                name="marketing_consultation", 
                description="Consults on marketing copy for retail products.",
                input_schema={"type": "object", "properties": {"text": {"type": "string"}}},
                output_schema={"type": "object", "properties": {"text": {"type": "string"}}},
                tags=["marketing"]
            )
        ],
        supports_authenticated_extended_card=False,
    )

    executor = MarketingAgentExecutor()
    task_store = InMemoryTaskStore()
    
    # 1. Create RequestHandler
    default_handler = DefaultRequestHandler(
        agent_executor=executor,
        task_store=task_store
    )
    
    # 2. Create JSON-RPC Handler
    jsonrpc_handler = JSONRPCHandler(
        agent_card=agent_card,
        request_handler=default_handler
    )
    
    # 3. Create Starlette App
    app = A2AStarletteApplication(
        agent_card=agent_card,
        http_handler=jsonrpc_handler
    ).build()
    
    return app

if __name__ == "__main__":
    # Usage: python -m marketing_app.server
    print("🚀 Starting Marketing Agent Server on http://localhost:8001")
    uvicorn.run(create_app(), host="localhost", port=8001)
